version: "3"
services:
  rust:
    container_name: rust
    build:
      context: .
    env_file:
      - .env.docker.default
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
